### ISSUE TITLE
The row unfolded button is not implemented

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [MohmmedAshraf/nova-fields-agent#1]
The row unfolded button that was presented on the animation is not implemented

![image](https://user-images.githubusercontent.com/57599426/72557543-a493ce80-38a9-11ea-8fce-f871b19b2166.png)

Thank you very much!

**Comment by MohmmedAshraf** [comment]
Hey, Sorry but could you provide more explain your issue.

**Comment by oleksandr-roskovynskyi** [comment]
These row items do not appear in the table!
![screenshot](https://user-images.githubusercontent.com/57599426/72677602-e76ec580-3aa6-11ea-9724-fe58118a1c77.png)

**Comment by MohmmedAshraf** [comment]
@oleksandr-roskovynskyi Oh, this is belongs to this package [Nova Sortable](https://github.com/optimistdigital/nova-sortable).
